2020-02-03 19:17:11,289 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-03 19:17:11,290 [ INFO ] Starting application...
2020-02-03 19:18:20,395 [ INFO ] Gracecfully shutting application down...
2020-02-03 19:18:20,697 [ INFO ] Stopped application
2020-02-03 19:23:15,940 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-03 19:23:15,940 [ INFO ] Starting application...
2020-02-03 19:23:56,214 [ INFO ] Gracecfully shutting application down...
2020-02-03 19:23:56,215 [ INFO ] Stopped application
2020-02-03 19:23:56,678 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-03 19:23:56,679 [ INFO ] Starting application...
2020-02-03 19:24:00,537 [ INFO ] Gracecfully shutting application down...
2020-02-03 19:24:00,538 [ INFO ] Stopped application
2020-02-03 19:24:06,104 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-03 19:24:06,105 [ INFO ] Starting application...
2020-02-03 19:24:30,998 [ INFO ] Gracecfully shutting application down...
2020-02-03 19:24:30,999 [ INFO ] Stopped application
2020-02-03 19:24:31,310 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-03 19:24:31,311 [ INFO ] Starting application...
2020-02-03 19:24:33,818 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-04 13:45:58,377 [ INFO ] Gracecfully shutting application down...
2020-02-04 13:45:58,379 [ INFO ] Stopped application
2020-02-08 13:34:46,925 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:34:46,926 [ INFO ] Starting application...
2020-02-08 13:34:49,635 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:34:49,636 [ INFO ] Stopped application
2020-02-08 13:35:54,970 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:35:54,971 [ INFO ] Starting application...
2020-02-08 13:35:55,880 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:36:29,615 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 10, in _
    m = StartUpMachine.from_user_id(ctx.user_id)
AttributeError: 'Context' object has no attribute 'user_id'
2020-02-08 13:37:27,532 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:37:27,534 [ INFO ] Stopped application
2020-02-08 13:37:28,264 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:37:28,265 [ INFO ] Starting application...
2020-02-08 13:37:29,001 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:40:05,309 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:40:05,311 [ INFO ] Stopped application
2020-02-08 13:40:05,845 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:40:05,846 [ INFO ] Starting application...
2020-02-08 13:40:06,622 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:40:09,946 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 15, in _
    m.sent_start()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 112, in _run
    self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't sent_start when in Entering password.
2020-02-08 13:40:45,862 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:40:45,864 [ INFO ] Stopped application
2020-02-08 13:40:46,332 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:40:46,332 [ INFO ] Starting application...
2020-02-08 13:40:47,013 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:40:50,066 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:40:50,068 [ INFO ] Stopped application
2020-02-08 13:40:54,514 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:40:54,515 [ INFO ] Starting application...
2020-02-08 13:40:55,234 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:41:41,196 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:41:41,197 [ INFO ] Stopped application
2020-02-08 13:41:41,637 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:41:41,638 [ INFO ] Starting application...
2020-02-08 13:41:42,378 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:41:48,939 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 60, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 10, in asd
    m.cycle()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 191, in _run
    transition = self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't cycle when in Entering school.
2020-02-08 13:43:27,627 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:43:27,628 [ INFO ] Stopped application
2020-02-08 13:43:28,139 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:43:28,140 [ INFO ] Starting application...
2020-02-08 13:43:28,858 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:43:37,573 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 60, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 11, in asd
    m.reset()
AttributeError: 'StartUpMachine' object has no attribute 'reset'
2020-02-08 13:57:29,215 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:57:29,216 [ INFO ] Stopped application
2020-02-08 13:57:29,843 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:57:29,843 [ INFO ] Starting application...
2020-02-08 13:57:30,544 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:57:34,607 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.sent_start()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 112, in _run
    self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't sent_start when in Entering school.
2020-02-08 13:58:12,760 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.sent_start()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 112, in _run
    self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't sent_start when in Entering school.
2020-02-08 13:58:15,123 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:58:15,125 [ INFO ] Stopped application
2020-02-08 13:58:15,662 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:58:15,663 [ INFO ] Starting application...
2020-02-08 13:58:16,441 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:59:36,464 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.reset()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 112, in _run
    self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't reset when in Entering login.
2020-02-08 13:59:46,769 [ INFO ] Gracecfully shutting application down...
2020-02-08 13:59:46,770 [ INFO ] Stopped application
2020-02-08 13:59:47,315 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 13:59:47,315 [ INFO ] Starting application...
2020-02-08 13:59:47,935 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 13:59:48,669 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 21, in _
    m = StartUpMachine.from_user_id(ctx.user_uid)
  File "/home/nm17/PycharmProjects/netschool_bot/state_logic.py", line 31, in from_user_id
    m = StartUpMachine(start_value=p)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 323, in __init__
    self.check()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 358, in check
    'Your currently have these: {!r}'.format(initials)))
statemachine.exceptions.InvalidDefinition: There should be one and only one initial state. Your currently have these: [State('Not started', identifier='reset', value='not_started', initial=True), State('Not started', identifier='reset', value='not_started', initial=True)]
2020-02-08 14:00:09,669 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:00:09,671 [ INFO ] Stopped application
2020-02-08 14:00:10,065 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:00:10,065 [ INFO ] Starting application...
2020-02-08 14:00:10,912 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:00:12,783 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 21, in _
    m = StartUpMachine.from_user_id(ctx.user_uid)
  File "/home/nm17/PycharmProjects/netschool_bot/state_logic.py", line 31, in from_user_id
    m = StartUpMachine(start_value=p)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 323, in __init__
    self.check()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 358, in check
    'Your currently have these: {!r}'.format(initials)))
statemachine.exceptions.InvalidDefinition: There should be one and only one initial state. Your currently have these: []
2020-02-08 14:00:30,587 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:00:30,589 [ INFO ] Stopped application
2020-02-08 14:00:30,945 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:00:30,946 [ INFO ] Starting application...
2020-02-08 14:00:31,632 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:00:34,700 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 21, in _
    m = StartUpMachine.from_user_id(ctx.user_uid)
  File "/home/nm17/PycharmProjects/netschool_bot/state_logic.py", line 31, in from_user_id
    m = StartUpMachine(start_value=p)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 323, in __init__
    self.check()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 358, in check
    'Your currently have these: {!r}'.format(initials)))
statemachine.exceptions.InvalidDefinition: There should be one and only one initial state. Your currently have these: []
2020-02-08 14:00:59,762 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:00:59,764 [ INFO ] Stopped application
2020-02-08 14:01:00,288 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:01:00,289 [ INFO ] Starting application...
2020-02-08 14:01:09,617 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:01:09,618 [ INFO ] Stopped application
2020-02-08 14:01:09,962 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:01:09,963 [ INFO ] Starting application...
2020-02-08 14:01:32,329 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:01:32,330 [ INFO ] Stopped application
2020-02-08 14:01:32,702 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:01:32,702 [ INFO ] Starting application...
2020-02-08 14:02:23,212 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:02:23,430 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.reset()
TypeError: 'NoneType' object is not callable
2020-02-08 14:02:28,816 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:02:28,817 [ INFO ] Stopped application
2020-02-08 14:02:29,452 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:02:29,453 [ INFO ] Starting application...
2020-02-08 14:02:30,116 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:02:34,176 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.reset()
TypeError: 'NoneType' object is not callable
2020-02-08 14:02:54,827 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:02:54,829 [ INFO ] Stopped application
2020-02-08 14:02:55,242 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:02:55,243 [ INFO ] Starting application...
2020-02-08 14:02:55,910 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:02:57,544 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 21, in _
    m = StartUpMachine.from_user_id(ctx.user_uid)
  File "/home/nm17/PycharmProjects/netschool_bot/state_logic.py", line 31, in from_user_id
    m = StartUpMachine(start_value=p)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 323, in __init__
    self.check()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 358, in check
    'Your currently have these: {!r}'.format(initials)))
statemachine.exceptions.InvalidDefinition: There should be one and only one initial state. Your currently have these: [State('Not started', identifier='reset', value='not_started', initial=True), State('Not started', identifier='reset', value='not_started', initial=True)]
2020-02-08 14:04:05,580 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:04:05,582 [ INFO ] Stopped application
2020-02-08 14:04:05,963 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:04:05,964 [ INFO ] Starting application...
2020-02-08 14:04:06,729 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:04:08,496 [ ERROR ] Exception while handling the update
Traceback (most recent call last):
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 138, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/kutana.py", line 157, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/kutana/router.py", line 104, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "/home/nm17/PycharmProjects/netschool_bot/plugins/echo.py", line 22, in _
    m.reset()
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 61, in __call__
    return self.func(*args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 85, in transition_callback
    return self._run(machine, *args, **kwargs)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 112, in _run
    self._verify_can_run(machine)
  File "/home/nm17/PycharmProjects/netschool_bot/venv/lib/python3.6/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run
    raise TransitionNotAllowed(self, machine.current_state)
statemachine.exceptions.TransitionNotAllowed: Can't reset when in Entering login.
2020-02-08 14:05:01,854 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:05:01,855 [ INFO ] Stopped application
2020-02-08 14:05:02,280 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:05:02,281 [ INFO ] Starting application...
2020-02-08 14:05:02,903 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:07:02,699 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:07:02,700 [ INFO ] Stopped application
2020-02-08 14:07:03,185 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:07:03,186 [ INFO ] Starting application...
2020-02-08 14:07:03,807 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:08:21,256 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:08:21,258 [ INFO ] Stopped application
2020-02-08 14:08:21,669 [ INFO ] Loaded plugin from "plugins/echo.py"
2020-02-08 14:08:21,670 [ INFO ] Starting application...
2020-02-08 14:08:22,312 [ INFO ] logged in as "Сетевой Город" ( https://t.me/netschoolbot )
2020-02-08 14:09:54,981 [ INFO ] Gracecfully shutting application down...
2020-02-08 14:09:54,983 [ INFO ] Stopped application
